# !/usr/bin/env python
# -*- coding: utf-8 -*-
# author: chen
# data:2020/12/28

import random
from datetime import datetime
from datetime import timedelta

# 语音坐席
AGENT_AUDIO = [
    ("1010", "黎攀登", "语音一组", "推广业务"),
    ("1011", "吴春如", "语音一组", "推广业务"),
    ("1012", "陈保兆", "语音一组", "推广业务"),
    ("1013", "潘启禾", "语音一组", "推广业务"),
    ("1014", "汪小娟", "语音二组", "电销业务"),
    ("1015", "祝玉永", "语音二组", "电销业务"),
    ("1016", "李牧哲", "语音二组", "电销业务"),
    ("1017", "谢鑫鑫", "语音三组", "售后业务"),
    ("1018", "徐栋梁", "语音三组", "售后业务"),
    ("1019", "任旺旺", "语音三组", "售后业务"),
]
# 文本坐席
AGENT_TEXT = [
    ("2020", "张兰霞", "文本一组", "销售业务"),
    ("2021", "陈江渝", "文本一组", "销售业务"),
    ("2022", "董超跃", "文本一组", "销售业务"),
    ("2023", "闫兆琪", "文本一组", "销售业务"),
    ("2024", "杨晶晶", "文本二组", "故障处理"),
    ("2025", "姚影影", "文本二组", "故障处理"),
    ("2026", "何梅梅", "文本二组", "故障处理"),
    ("2027", "王玉洁", "文本三组", "业务续期"),
    ("2028", "杨良琴", "文本三组", "业务续期"),
    ("2029", "刘国倩", "文本三组", "业务续期"),
]
# 客户信息
CUSTOMERS = [
    ("金蒙蒙", "13223654087"), ("宋怀顺", "18585693217"), ("谢怡平", "13049837605"), ("张三健", "13110849657"),
    ("郑宪威", "18539715628"), ("朱章章", "18897168024"), ("濮仁涛", "13304545676"), ("钱生旺", "14701853962"),
    ("张振康", "18539715628"), ("梁荣中", "13324545679"), ("黄勇强", "13304545680"), ("程艳奇", "13958740293"),
    ("闻园杰", "13380726954"), ("潘大超", "13850942168"), ("谭天信", "15956781402"), ("陈家俊", "13505736914"),
    ("邹嘉乐", "15321835497"), ("赵迎康", "15826839145"), ("王学锋", "18224076583"), ("王佳华", "15984059627"),
    ("翁信仰", "13304545690"), ("李景全", "18224076583"), ("许圳庭", "15581640527"), ("丘振华", "14728475691"),
    ("刘志栋", "13637419586"), ("李樟洪", "18852961740"), ("田梅生", "13314545696"), ("吴立鹏", "13304543697"),
    ("刘西西", "13374545698"), ("巫永腾", "13334545693"), ("刁佳林", "18992730148"), ("孙利杨", "13169725138"),
    ("陈晓涛", "15318743509"), ("凡小春", "15532709518"), ("高以鹏", "13304545698"), ("朱富来", "13186345170")
]
# 语音存放地址
AUDIOS = [
    ("http://172.16.20.185:8248/public/audio/200921182.mp3", 734),
    ("http://172.16.20.185:8248/public/audio/20092016514957210001015200036b.mp3", 88),
    ("http://172.16.20.185:8248/public/audio/2009210925442188000101960003e7ec.mp3", 242),
    ("http://172.16.20.185:8248/public/audio/2009210937388828000101530003d71d.mp3", 227),
    ("http://172.16.20.185:8248/public/audio/2009210938215898000104800003e37f.mp3", 163),
    ("http://172.16.20.185:8248/public/audio/2009210938490871000104800003e39b.mp3", 124),
    ("http://172.16.20.185:8248/public/audio/2009210938558492000102480003e538.mp3", 200),
    ("http://172.16.20.185:8248/public/audio/2009210940388446000104800003e3f5.mp3", 93),
    ("http://172.16.20.185:8248/public/audio/2009210942043939000102430003d95a.mp3", 157),
    ("http://172.16.20.185:8248/public/audio/2009210943101694000104800003e459.mp3", 157),
]
# # 数据推送地址
# See_105 = 'http://172.16.20.105:8248/api/v1/external/workOrder/sendExternalData'
# See_185 = 'http://172.16.20.185:8248/api/v1/external/workOrder/sendExternalData'

ADD_KEYWORD = ["您好", "亲", "亲爱的", "您好啊", "早上好", "下午好", "晚上好", "尊敬的客户", "Hello", "Hi"]
DEL_KEYWORD = ["滚蛋", "滚", "讨厌", "怎么了", "招人烦", "滚滚滚", "又是你", "烦", "烦人", "不行"]


# 文本会话信息
def content_list_v3_perftest(agent_name, customer, start_time, end_time):
    perf_list = [
            {
                "content": "您好！您已进入人工服务，客服人员小静为您服务中，请问有什么问题？",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(1, 4))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(1, 4))), "%Y-%m-%d %H:%M:%S"),

            },
            {

                "content": "请问我在小程序下的订单没办法开发票吗？",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(3, 5))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(3, 5))), "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "您好，现在为您查询一下，可能需要1-2分钟的时间，请您稍等。",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(6, 8))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(6, 8))), "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "好的，谢谢，麻烦你了",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(13, 16))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(13, 16))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "非常抱歉让您久等了。亲亲，在您账号中没有看到这笔订单呢，请问是其他手机号下单的吗?",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(15, 17))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(15, 17))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "我只有一个手机号",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(19, 21))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(19, 21))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "您好，这是该城市小面车的车厢的规格呢，请您参考下，具体以师傅车型为准呢",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(24, 26))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(24, 26))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "请问泉州市安溪县湖头镇有货拉拉的服务点吗",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(26, 27))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(26, 27))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "查看到了，是还在开票中的呢 ，亲亲，您申请后在24小时发送您的邮箱的呢  烦请等等哈",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(27, 29))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(27, 29))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "请问您一张1.5m的床加上一个6kg的洗衣机大概需要叫什么车？",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(30, 35))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(30, 35))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "可以的，到时候您直接跟司机师傅说就可以了，司机师傅会安排的",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(34, 42))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(34, 42))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "好的，那我一会儿给司机师傅打电话就可以了，到时候我们沟通联系",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(40, 44))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(40, 44))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "请问您咨询的是哪笔订单？点击下方【选择订单】按钮选择咨询的订单。若无相关订单，可在APP查询并提供截图或订单号后6位。",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(44, 45))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(44, 45))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "订单编号:154164557743，成都市双流区-华阳街道天府大道南段1397号",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(44, 45))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(44, 45))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "请问您想了解的是泉州市安溪县湖头镇有货拉拉的服务点吗",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(45, 47))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(45, 47))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "贵州高投服务管理有限公司，贵州省内所有服务区配送货",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(48, 52))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(48, 52))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "请问您的床可以拆卸的吗？如果不可拆卸需要加钱，如果可以拆卸加的钱就比较少",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(50, 54))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(50, 54))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "那到底需要加多少钱呢，之前说的是不用加钱啊，加太多我就选别人家的了",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(55, 58))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(55, 58))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "感谢您对平台的关注，麻烦您提供下您的公司名、联系人、联系号码、合作内容等信息的噢，稍后我这边为您记录反馈呢",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(58, 62))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(58, 62))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "你还是先帮忙确认一下吧，不然定了有退单",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(62, 63))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(62, 63))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "请您放心，在您下单成功后，平台会将您的订单推送给附近司机的",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(63, 64))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(63, 64))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "这边折叠起来是1.48米的哦，折叠起来的宽度是1.01米的",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(67, 70))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(67, 70))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "您好，在您点击【现在用车】或【预约用车】后，会跳转到确认订单的页面",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(70, 74))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(70, 74))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "请问具体应该如何确认呢",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(80, 82))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(80, 82))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "然后请您提供一下需要修改的发票信息以及邮箱号的呢",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(82, 85))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(82, 85))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "能不能退款呢，我不想定这个车了",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(87, 92))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(87, 92))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "师傅，抱歉的，目前会员是无法退款，但是如确实疫情严重可以申请暂停会员的，请问有没有您当地的隔离或封区域的凭证的呢",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(92, 93))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(92, 93))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "没有啊，当时没有给我开的隔离或封区域的凭证",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(93, 95))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(93, 95))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "温馨提醒：如果您需要发票的话，建议通过APP下单，下单的时候勾选承运服务即可在订单完成的48小时后开具发票",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(97, 102))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(97, 102))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "好的，那我试一试",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(100, 104))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(100, 104))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "亲亲，我们平台的师傅都是经过严格的上岗培训，并且都是实名认证的。",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(104, 105))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(104, 105))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "那如果在运输途中出现货物损坏或丢失情况，我应该怎么处理呢？",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(105, 109))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(105, 109))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "如果在运输途中出现货物损坏或丢失情况，我们平台也会积极协助您与师傅处理后续的赔偿等事宜的呢",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(109, 110))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(109, 110))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "好的，那我就放心了",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(114, 115))),
                                          "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(114, 115))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "温馨提醒您：若致电司机，为了确保开车安全，请尽量缩短通话时长哦~，感谢您的理解和配合！",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(116, 118))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(116, 118))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "好的，那是一定的",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(119, 120))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(119, 120))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "亲亲，您的支持就是我前进的动力，如您对我的服务觉得满意，麻烦您给我一个好评哦~",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(122, 124))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(122, 124))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "对了，石家庄疫情会费可不可以退回一部分",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(125, 126))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(125, 126))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "师傅，受疫情影响，为了更好的保护您和家人的健康，您请放心，在此期间您的会员费不会进行扣减。",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(128, 130))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(128, 130))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "查下我的账号行为分还能增长么? 没有平台推送学习任务增长行为分么",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(131, 133))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(131, 133))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "目前行为分低的会导致综合抢单成功功率降低的呢，目前无法再增长了呢",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(135, 138))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(135, 138))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "12.31号没有接单，但是扣款了，到现在没有退回，是什么原因",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(139, 140))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(139, 140))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "师傅您好，平台现推出拉货宝服务，每天只需1块钱，就能为您提供人身和货物保障",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(142, 144))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(142, 144))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "查询订单也没有看到，12.31号进系统不了",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(145, 147))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(145, 147))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "您好，运送过程中所产生的高速/停车/过桥过路费等额外费用以实际产生的进行支付的哦",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(148, 150))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(148, 150))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "没有平台推送学习任务增长行为分么？四个好评也不会涨一分行为分么？",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(151, 153))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(151, 153))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "师傅也可以在APP【我的】-【行为分】-【了解行为分】查看详情的呢",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(155, 156))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(155, 156))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "查询订单也没有看到，12.31号进系统不了，这5笔都是扣款了，但是没有退回来",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(158, 160))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(158, 160))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "您好，正在为您查询，可能需要1-2分钟的时间，请您稍等哦。",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(162, 163))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(162, 163))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "司机师傅说他在楼下等了1小时，需要支付他费用，这本身就是不合理的啊",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(164, 166))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(164, 166))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "您好，感谢您的耐心等待。师傅您好，行为分40分及以下就会被封号的呢，目前经查看师傅您的行为分已经是0分的哦 ~",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(168, 169))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(168, 169))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "你可以不下那些任务奖励，下了任务奖励又收回去，你们这种是人操作的吗",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(170, 172))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(170, 172))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "请您消消气，订单是系统进行推送，然后按照附近5公里内的师傅接单服务的呢，可能附近的师傅比较少的呢，建议您再耐心等待下的呢~",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(173, 174))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(173, 174))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "地图上显示附近有很多车辆，为什么没有人接单",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(176, 178))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(176, 178))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "抱歉给您带来不便的呢， 目前是根据您用车需求推送通知附近的师傅接单的哦",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(179, 180))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(179, 180))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "我都加20小费了，还是没有师傅",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(181, 183))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(181, 183))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "理解您的心情哦，如添加小费仍未有司机接单的，可能是推送时间长的哦，如果长时间无人接单，建议您可以取消订单重新下单，我们会重新进行订单推送的呢",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(184, 185))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(184, 185))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "为什么我下单给司机跑，跑完了系统判司机刷单",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(186, 188))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(186, 188))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "您点击这个下面去看下订单，31号有没有操作下过订单的",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(189, 190))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(189, 190))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "12.31号没有接单，但是扣款了，到现在没有退回，是什么原因",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(191, 193))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(191, 193))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "请问您咨询的是哪笔订单？点击下方【选择订单】按钮选择咨询的订单。若无相关订单，可在APP查询并提供截图或订单号后6位。",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(193, 195))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(193, 195))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "你好，我刚刚在平台上叫了依维柯，但是发现货物准备出问题了，司机说这个需要支付他误工费",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(196, 198))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(196, 198))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "嗯嗯，我会为您登记反馈处理的，请您后续留意账单情况",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(199, 201))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(199, 201))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "这个误工费要怎么算？",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(202, 205))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(202, 205))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "十分抱歉给您带来不愉快的用车体验呢，平台是没有相关误工费的收费标准的呢",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(206, 207))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(206, 207))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "那这个司机师傅说我要付给他钱，司机师傅说他在楼下等了1小时，需要支付他费用",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(208, 210))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(208, 210))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "如是司机实际已经出发至您的发货点，您取消订单，建议司机可以进线反馈呢",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(211, 213))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(211, 213))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "什么意思？进线反馈是啥意思？在吗？能不能说句话哦？",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(214, 215))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(214, 215))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "如司机产生空跑，建议您可以让司机进线反馈呢，目前平台是没有相关空跑费用收费标准的",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(216, 217))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(216, 217))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "让司机在线和你们客服反馈",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(218, 220))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(218, 220))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "建议您可以让司机进线反馈相关订单情况呢，请您放心，平台会核实情况，建议您后续手机畅通留意",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(221, 223))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(221, 223))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "你说的进线反馈是什么意思，太专业听不懂",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(224, 226))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(224, 226))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "如司机对此空跑有异议，需要您支付费用，建议您可以让司机进线咨询呢，目前平台是无相关空跑收费标准的呢",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(228, 230))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(228, 230))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "可以看到聊天记录吗，我这个单子是有返程服务的",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(231, 233))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(231, 233))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "给您造成的不便非常报歉，让您久等了，请问师傅没有返程吗？",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(234, 235))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(234, 235))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "我要投诉",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(236, 238))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(236, 238))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "非常抱歉，给您带来不好的体验，希望您也不要因此而影响到您的心情",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(239, 241))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(239, 241))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "是啊，我的东西还在他车上，他意思我不加钱他就要接其他单子了",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(242, 244))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(242, 244))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "我非常理解您的感受，请您先消消气，平台向您致歉，对于师傅平台也会管控处理的呢。",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(245, 246))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(245, 246))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "我要求他现在就把我的货给我拿回来。而不是他半夜有空了再拉回来",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(248, 250))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(248, 250))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "给您造成的不便非常报歉，请问货物在师傅车上 师傅不愿意运送还给您吗？",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(251, 252))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(251, 252))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "我用货拉拉都几年了从来没碰到这样的情况。而且我备注了有返程。",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(254, 255))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(254, 255))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "非常抱歉，给您带来不好的体验，希望您也不要因此而影响到您的心情",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(256, 258))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(256, 258))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "请问能联系上师傅吗？你们自己去联系吧，他说话太粗鲁了",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(259, 260))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(259, 260))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "请问师傅向您收取多少钱 才愿意把货物送还给您呢 ？",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(261, 262))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(261, 262))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "你们不能联系师傅责令他把货送回来吗",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(263, 264))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(263, 264))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "一般我们处理专员会在24小时左右联系您，请您保持手机畅通，耐心等待留意接听来电。    ",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(266, 268))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(266, 268))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "司机接完订单后失联，打电话也不接！",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(269, 272))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(269, 272))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "您是投诉司机爽约是吗，请您放心，司机爽约我会为您反馈上去处理，您24小时留意接听电话即可的哦",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(273, 275))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(273, 275))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "北京这么冷的天不来跟我说一下我就赶紧换司机就行了啊",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(276, 278))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(276, 278))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "非常抱歉给您带来不愉快的用车体验了，请您放心，平台会核实情况，建议您后续手机畅通留意",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(279, 281))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(279, 281))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "什么意思啊！你们就这么管理司机的吗？过分",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(282, 283))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(282, 283))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "我非常理解您的感受，请您先消消气，平台向您致歉，对于师傅平台也会管控处理的呢。",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(284, 285))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(284, 285))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "请您放心，平台会核实情况，建议您后续手机畅通留意",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(286, 288))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(286, 288))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "还有一个问题，基本上每一个订单都会超出平台定价",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(289, 291))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(289, 291))),

                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "师傅您辛苦了，您的情况我这边已了解，请不用担心，建议您先完成订单，",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(293, 295))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(293, 295))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "在订单完成后再进线联系我们呢，并保留好有效的行驶轨迹的导航凭证，为确保有行车轨迹，请您一定要打开GPS哦。",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(296, 298))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(296, 298))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "平台定价111，一导航140多",
                "messageType": 1,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(299, 301))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(299, 301))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "师傅您好，由于您的订单还没有完成，我们无法计算最终的里程差值，建议您先完成订单",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(302, 305))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(302, 305))),
                                             "%Y-%m-%d %H:%M:%S"),
            },
            {
                "content": "您的支持就是我前进的动力，如您对本次问题的解答觉得满意，麻烦您给我一个好评哦，祝您生活愉快~",
                "messageType": 2,
                "startTime": datetime.strftime((start_time + timedelta(seconds=random.randint(303, 305))),
                                               "%Y-%m-%d %H:%M:%S"),
                "endTime": datetime.strftime((end_time + timedelta(seconds=random.randint(303, 305))),
                                             "%Y-%m-%d %H:%M:%S"),
            }]
    # print(perf_list)
    return perf_list


